clear; clc;
figure('Color','w');
Ln=10; sim('task_G_mod');
subplot(2,1,1); hold on;
plot(x.time,x.data,'-','Color','black','LineWidth',1);
plot(xn.time,xn.data,':','Color','black','LineWidth',2);
legend('without noise','with noise');
FormatCharts('$$t,{\textrm s}$$','$$x(t)$$','10\% noise');
subplot(2,1,2); hold on;
plot(Sxdt.time,Sxdt.data,'-','Color','black','LineWidth',1);
plot(Sxndt.time,Sxndt.data,':','Color','black','LineWidth',2);
legend('without noise','with noise','filtered');
FormatCharts('$$t,{\textrm s}$$','$$\int{x(t)dt}$$','10\% noise');
figure('Color','w');
Ln=1; sim('task_G_mod');
subplot(2,1,1); hold on;
plot(x.time,x.data,'-','Color','black','LineWidth',1);
plot(xn.time,xn.data,':','Color','black','LineWidth',2);
legend('without noise','with noise');
FormatCharts('$$t,{\textrm s}$$','$$x(t)$$','1\% noise');
subplot(2,1,2); hold on;
plot(Sxdt.time,Sxdt.data,'-','Color','black','LineWidth',1);
plot(Sxndt.time,Sxndt.data,':','Color','black','LineWidth',2);
legend('without noise','with noise','filtered');
FormatCharts('$$t,{\textrm s}$$','$$\int{x(t)dt}$$','1\% noise');
