clear; clc;
figure('Color','w');
Ln=10; sim('task_A_mod');
subplot(2,1,1); hold on;
plot(x.time,x.data,'-','Color','black','LineWidth',2);
plot(xn.time,xn.data,':','Color','black','LineWidth',2);
legend('without noise','with noise');
FormatCharts('$$t,{\textrm s}$$','$$x(t)$$','10\% noise');
subplot(2,1,2); hold on;
plot(dxdt.time,dxdt.data,'-','Color','black','LineWidth',2);
plot(dxndt.time,dxndt.data,':','Color','black','LineWidth',2);
legend('without noise','with noise','filtered');
FormatCharts('$$t,{\textrm s}$$','$$\frac{dx}{dt}(t)$$','10\% noise');
figure('Color','w');
Ln=1; sim('task_A_mod');
subplot(2,1,1); hold on;
plot(x.time,x.data,'-','Color','black','LineWidth',2);
plot(xn.time,xn.data,':','Color','black','LineWidth',2);
legend('without noise','with noise');
FormatCharts('$$t,{\textrm s}$$','$$x(t)$$','1\% noise');
subplot(2,1,2); hold on;
plot(dxdt.time,dxdt.data,'-','Color','black','LineWidth',2);
plot(dxndt.time,dxndt.data,':','Color','black','LineWidth',2);
legend('without noise','with noise','filtered');
FormatCharts('$$t,{\textrm s}$$','$$\frac{dx}{dt}(t)$$','1\% noise');
